# Generated by Django 2.2 on 2020-10-26 06:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('symbol', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('symbol_fa', models.CharField(max_length=30)),
                ('name_fa', models.CharField(max_length=30)),
                ('industry_index', models.CharField(max_length=50, null=True)),
                ('exchange', models.CharField(max_length=30)),
                ('type_code', models.IntegerField()),
                ('company_key', models.IntegerField(null=True)),
                ('company_type', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(max_length=30)),
                ('board', models.IntegerField(null=True)),
                ('market', models.IntegerField(null=True)),
                ('company_code', models.CharField(max_length=30, null=True)),
                ('industry_tse', models.IntegerField()),
                ('industry_bourseview', models.IntegerField()),
                ('last_update_data', models.DateTimeField(null=True)),
                ('indicators_lastupdate', models.DateTimeField(default=datetime.datetime(2018, 10, 27, 6, 4, 33, 790181, tzinfo=utc), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdjustedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=4)),
                ('time', models.DateTimeField(max_length=30)),
                ('open_adjusted', models.IntegerField(null=True)),
                ('high_adjusted', models.IntegerField(null=True)),
                ('low_adjusted', models.IntegerField(null=True)),
                ('close_adjusted', models.IntegerField(null=True)),
                ('vwap_adjusted', models.IntegerField(null=True)),
                ('vwap_adjusted_previous', models.IntegerField(null=True)),
                ('volume', models.BigIntegerField()),
                ('value', models.BigIntegerField()),
                ('num_of_trades', models.IntegerField()),
                ('adj_coef', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='var.Stock')),
            ],
        ),
    ]
