# Generated by Django 2.2 on 2020-10-26 06:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('var', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='indicators_lastupdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 6, 7, 3, 185173, tzinfo=utc), null=True),
        ),
    ]
